//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class hesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hesap()
        {
            this.hesapDefteri = new HashSet<hesapDefteri>();
        }
    
        public int hesapID { get; set; }
        public string ibanNo { get; set; }
        public string hesapNo { get; set; }
        public int hesapPara { get; set; }
        public string musteriNo { get; set; }
        public string hesapOlusturmaTarihi { get; set; }
    
        public virtual musteri musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hesapDefteri> hesapDefteri { get; set; }
    }
}
