//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class hesapDefteri
    {
        public int hesapDefteriNo { get; set; }
        public Nullable<int> hesapTutari { get; set; }
        public string hesapTutarGirisi { get; set; }
        public string hesapDefteriTarih { get; set; }
        public Nullable<int> hesapId { get; set; }
    
        public virtual hesap hesap { get; set; }
    }
}
