//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class krediKartiHarcanan
    {
        public int krediKartiHarcamaNo { get; set; }
        public string krediKartiHarccananTutar { get; set; }
        public Nullable<int> krediKartiNo { get; set; }
        public string Kategori { get; set; }
    }
}
