//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class krediKarti
    {
        public int krediKartiID { get; set; }
        public string krediKartiNo { get; set; }
        public Nullable<int> krediKartiLimit { get; set; }
        public Nullable<int> krediKartıHarcanananTutar { get; set; }
        public Nullable<int> krediKartiKalanTutar { get; set; }
        public string musteriNo { get; set; }
    
        public virtual musteri musteri { get; set; }
    }
}
