//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciNo { get; set; }
        public string kullaniciAd { get; set; }
        public string kullaniciSoyad { get; set; }
        public string dogumyili { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSifre { get; set; }
        public string kullaniciMail { get; set; }
        public Nullable<bool> kullaniciAktifMi { get; set; }
        public string kullaniciTc { get; set; }
        public Nullable<int> kullaniciRol { get; set; }
    
        public virtual kullanicRol kullanicRol { get; set; }
    }
}
