//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class miniBankaOtomasyonuDBEntities : DbContext
    {
        public miniBankaOtomasyonuDBEntities()
            : base("name=miniBankaOtomasyonuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hesap> hesap { get; set; }
        public virtual DbSet<hesapDefteri> hesapDefteri { get; set; }
        public virtual DbSet<krediKarti> krediKarti { get; set; }
        public virtual DbSet<krediKartiHarcanan> krediKartiHarcanan { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<kullanicRol> kullanicRol { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
